"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.estasTabelo = exports.da = exports.de = exports.longeco = exports.lokaSignovicigi = exports.signovicigi = exports.valoroj = exports.malmovi = exports.splisi = exports.klasi = exports.kelke = exports.tranĉi = exports.movi = exports.inversigi = exports.dekstraRedukti = exports.redukti = exports.pusxi = exports.puŝi = exports.kraketi = exports.mapi = exports.lastaIndeksoDe = exports.klavoj = exports.unuigi = exports.indeksoDe = exports.inkluzivas = exports.porCxiu = exports.porĈiu = exports.plataMapi = exports.platigi = exports.troviIndekso = exports.trovi = exports.filtri = exports.plenigi = exports.cxiu = exports.ĉiu = exports.eniroj = exports.moviMemoron = exports.interligi = void 0;
const core_1 = __importDefault(require("@localized/core"));
const { array } = core_1.default;
exports.interligi = array.concat();
exports.moviMemoron = array.copyWithin();
exports.eniroj = array.entries();
exports.ĉiu = array.every();
exports.cxiu = exports.ĉiu;
exports.plenigi = array.fill();
exports.filtri = array.filter();
exports.trovi = array.find();
exports.troviIndekso = array.findIndex();
exports.platigi = array.flat();
exports.plataMapi = array.flatMap();
exports.porĈiu = array.forEach();
exports.porCxiu = exports.porĈiu;
exports.inkluzivas = array.includes();
exports.indeksoDe = array.indexOf();
exports.unuigi = array.join();
exports.klavoj = array.keys();
exports.lastaIndeksoDe = array.lastIndexOf();
exports.mapi = array.map();
exports.kraketi = array.pop();
exports.puŝi = array.push();
exports.pusxi = exports.puŝi;
exports.redukti = array.reduce();
exports.dekstraRedukti = array.reduceRight();
exports.inversigi = array.reverse();
exports.movi = array.shift();
exports.tranĉi = array.slice();
exports.kelke = array.some();
exports.klasi = array.sort();
exports.splisi = array.splice();
exports.malmovi = array.unshift();
exports.valoroj = array.values();
exports.signovicigi = array.toString();
exports.lokaSignovicigi = array.toString();
exports.longeco = array.length();
exports.de = array.from();
exports.da = array.of();
exports.estasTabelo = array.isArray();
